# Generated by Django 3.2.8 on 2021-10-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'CarModel',
                'verbose_name_plural': 'CarModels',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('phone_number', models.IntegerField(default='XX XXX-XX-XX')),
                ('passport', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Automatic', 'Automatic'), ('Mechanic', 'Mechanic'), ('Electronic', 'Electronic')], max_length=100)),
                ('position', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, null=True)),
                ('production', models.CharField(choices=[('Local', 'Local'), ('Export', 'Export'), ('Import', 'Import')], max_length=100)),
                ('year', models.IntegerField(default=2021)),
                ('color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('White', 'White'), ('Black', 'Black'), ('Pink', 'Pink')], max_length=100)),
                ('status', models.CharField(choices=[('In Order', 'In Order'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('In Way', 'In Way'), ('Order Completed', 'Order Completed')], max_length=100)),
                ('Additional', models.TextField(max_length=1000)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autosalon.carmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='autosalon.user')),
            ],
        ),
    ]
