# Generated by Django 3.2.8 on 2021-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autosalon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
